### PR TITLE
Create badges after GamificationInterface create

### PR DESCRIPTION
**Pull request by Ion-Petcu**
Resolves issue https://github.com/mattjegan/django-gamification/issues/12

### CODE REVIEW

**Comment by mattjegan** [comment]
Hey, thanks for the PR 😄  Looks pretty good to me, could you please fix the merge conflicts before this goes in?

**Comment by Ion-Petcu** [comment]
Added similar functionality for Unlockable objects. https://github.com/mattjegan/django-gamification/issues/12

**Comment by mattjegan** [comment]
Awesome, thanks for all the help 😄  Are you actively using this package @Ion-Petcu ?

**Comment by Ion-Petcu** [comment]
You're welcome! 😄 Unfortunately, I am not using this package at the moment, but I am an active Django user so I chose this project for Hacktoberfest. It's a good idea and I think it has a lot of potential for small projects. Good luck! 👍

**Pull request merged**
